# Site settings
title: ExFunTube
email: dayoon.ko@vision.snu.ac.kr
url: https://github.com/exfuntube.github.io
description: "description : Can Language Models Laugh at YouTube Short-form Videos? [EMNLP 2023]"
keywords: "keywords, your keywords, separated by commas"
skills: "Can Language Models Laugh at YouTube Short-form Videos? [EMNLP 2023]"
meta_author: Ko Dayoon

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2c3e50 #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 7DC6B8  #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/dayoon-ko/ExFunTube

# Postal address (add as many lines as necessary)
address:
  - line: 1 Gwanak-ro, Gwanak-gu Seoul
  - line: 08826 South Korea

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
